### ISSUE TITLE
Test for KrisJ

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels-a11y-publishing#10]
Just testing setup. I've sent info to LB and FL to come and take a look as well.

**Comment by zwettemaan** [comment]
Test seems to work - reading ya loud and clear!

**Comment by zwettemaan** [comment]
I'll leave this open for now and wait for LB and FL to add some comments to this, after which I'll close this issue...

**Comment by kpjorgen** [comment]
Perfect! Thanks!

**Comment by zwettemaan** [comment]
I assigne flittle8 which I assume is Farrah. @kpjorgen, do you know Laura's account name?

**Comment by kpjorgen** [comment]
Yes, that is Farrah -- thanks. And with Laura, I've contacted her and gave her the details to setup an account, but have not head back, yet. I will let you know as soon as she lights an account up:)

**Comment by flittle8** [comment]
@kpjorgen @zwettemaan I can take a look through these issues next week while I'm at ebookcraft. I think Laura will also be there, so I'll see if we can set aside some time to look at this together. thanks!

**Comment by zwettemaan** [comment]
@flittle8 Great stuff! None of these issues is 'blocked' on your input, but the more info, sample files, peripheral info.... you can provide, the better... Otherwise, we'll rely purely on how accurate my imagination is ;-)

**Comment by LauraB7** [comment]
Hello everyone. Meeting now with Farrah at ebookcraft to go over this project.

**Comment by LauraB7** [comment]
I will start to upload samples -- InDesign files or EPUB files where relevant -- to all of the issues in the next few days.

**Comment by zwettemaan** [comment]
Hi Laura, welcome to the team! Closing this issue off now - we're all on board methinks!
