### ISSUE TITLE
Style Cleanup: There was no Markdown file generated?

### ISSUE THREAD

**Issue by zwettemaan** [BCLibCoop/nnels-a11y-publishing#12]
See #7 for sample file

**Comment by zwettemaan** [comment]
@LauraB7 As far as I can tell the Markdown file is created. 

<img width="591" alt="Screen Shot 2019-04-11 at 11 10 48 AM" src="https://user-images.githubusercontent.com/3396477/55919643-e3c22e80-5c4a-11e9-8b10-c0c6d1c4f67f.png">

But I noticed the file is InDesign CC 2017. 

If you happen to open this file in CC 2018 or CC 2019 you _must_ save it first (because you're upgrading the file to a higher version and you end up with a brand new unsaved document). 

That's how InDesign works: opening an older file in a newer version gives you a brand new, never saved document.

Because the document is unsaved, there is no 'home' location for it yet, so the script has no way to know where you want the Markdown file (it wants to save it 'next to' the InDesign file).

By saving the InDesign file, it finds a 'home' and the Markdown file should appear.

Let me know if that could be the issue. If so, maybe my docs are not clear enough; I'll stress this point a bit more.

**Comment by zwettemaan** [comment]
@LauraB7, if this fixes the issue, can you click the 'Close' button below and close this issue? Thx!

**Comment by LauraB7** [comment]
Hi @zwettemaan. I ran the script again from InDesign 13.1 from a file saved on my desktop. I don't see a Markdown file? Do I need to update InDesign?

**Comment by zwettemaan** [comment]
Hmm... Odd one. It works for me. Here's a recording of how it is meant to work. Any clues as to what might be different on your system?


[StyleCleanupMarkdownDemo.mp4.zip](https://github.com/BCLibCoop/nnels-a11y-publishing/files/3070542/StyleCleanupMarkdownDemo.mp4.zip)

**Comment by LauraB7** [comment]
I did the exact same you did in the video. And did not get a Markdown file. But I tested with a different file and it did work. Soooo.... Issue closed?

**Comment by zwettemaan** [comment]
Hmm... Probably. 

Can you search your hard disk for any recent .md files? What happens to me at times is that I inadvertently save somewhere else than where I think I saved, and then the .md file would end up there, rather than where I think it would be. E.g. if the original file is on 'Desktop', but you accidentally resave inside 'Documents', then you'd still see the old file on Desktop but the .md file would appear inside Documents, making it seem it's not there. If you search for a recently created .md file we could find out if that might be what happened.

**Comment by zwettemaan** [comment]
I want to rule out that we are not looking at a silent script crash: i.e. if the script conks out before it's fully finished, we'd not see a Markdown file either. In that case, I'd need to see the document; it might have some unexpected condition that the script cannot yet handle.

**Comment by LauraB7** [comment]
I can't find a rogue .md file. Sorry.

**Comment by zwettemaan** [comment]
Can you share the .indd file with me? It's OK to email or DropBox it if you prefer - I can delete it once I figured out what's up. I'll set up a shared DropBox folder between us - look out for an invite...

**Comment by LauraB7** [comment]
It is the same War/Torn file that you already have. I think it must be an anomaly. I tend to find the edge cases right from the start, you know.

**Comment by zwettemaan** [comment]
Hmm... Keep an eye out for when/if this issue reoccurs. Maybe it's a font issue. I get a warning about missing fonts, so my setup is probably not 100% identical to yours. 

What you can also do is change the script into debug mode. If you open the script in a text editor, you'll see something like:

<img width="780" alt="Screen Shot 2019-04-12 at 10 18 57 AM" src="https://user-images.githubusercontent.com/3396477/55996773-7545a500-5d0c-11e9-8caf-f9cb843bc482.png">

Change the following lines.

Change 0 -> 1:
```
...
var DEBUG              = 1;
...
```
Change 0 -> 4
```
...
var LOG_LEVEL          = 4; 
...
```
Set a file path for a log file:
```
...
var FILE_PATH_LOG      = "~/Desktop/StyleCleanup.log";
...
```

Then go through the same motions again. If all went well, a file 'StyleCleanup.log' should appear on your desktop - that file is of interest to me.

**Comment by flittle8** [comment]
@zwettemaan is it safe to assume that this StyleCleanup.jsx is an InDesign specific script, or can I run this on an EPUB file outside ID?

**Comment by zwettemaan** [comment]
@flittle8 That is correct! StyleCleanup.jsx is a pre-export operation. It is a tool used with InDesign to alleviate some bad styling (or no styling at all) in the InDesign document before it is exported to EPUB. 

Afterwards, the EPUB export should be a lot cleaner.
