### ISSUE TITLE
DropToScript does not work on Mac OS X

### ISSUE THREAD

**Issue by zwettemaan** [BCLibCoop/nnels-a11y-publishing#16]
This might be related to the Mac OS X version. Farrah is using 10.11.x (El Capitan).

**Comment by zwettemaan** [comment]
@flittle8 I had another thought. What is the setting of your Security & Privacy control panel? 

Go to System Preferences, click Security & Privacy. What does it say for 'Allow apps...'? It should say App Store and identified developers'. If not, you need to click the lock and change it...


<img width="652" alt="Screen Shot 2019-05-03 at 6 55 59 PM" src="https://user-images.githubusercontent.com/3396477/57123271-4f746300-6dd5-11e9-9781-1348d09de109.png">

**Comment by flittle8** [comment]
@zwettemaan Yes, those are my settings: "App Store and identified developers"

**Comment by zwettemaan** [comment]
@flittle8 I managed to set up Mac OS X El Capitan, and tried it out, and it all works. Grm.

Would you be willing to do a screenshare some time next week. I'd want to take control over your system and poke and prod a bit to get an idea of what is going on.

**Comment by flittle8** [comment]
@zwettemaan Sure let’s do it. When works for you? I’m currently in the UK time zone.

**Comment by zwettemaan** [comment]
I'll send you a Doodle (scheduling) invite. It'll be late evening for me, early morning for you.

**Comment by zwettemaan** [comment]
Ok, we figured it out. DropToScript was accidentally configured with a default script. If and when that happens, dropping an item onto DropToScript will auto-select that script and provide no UI. 

So the DropToScript was working, but because a default script was selected, no feedback was given.

Morale: I'll add some more feedback to the DropToScript and make it show a report of how many, if any, files it processed. That way the user can tell whether the program really did not work vs silently went to do its business.
