### ISSUE TITLE
Means by which to easily wipe out all style overrides

### ISSUE THREAD

**Issue by zwettemaan** [BCLibCoop/nnels-a11y-publishing#7]

**Comment by zwettemaan** [comment]
(Script in InDesign)

**Comment by zwettemaan** [comment]
This one is fairly straightforward. I've written similar scripts before.

What I intend to do:

Run script -> script checks all the text in the document and looks for any manual overrides. These are changes in font, color, font size, aligmnent,... that are not part of the assigned style. For each of these changes, it either will replace them with an existing style with proper attributes, or will create a new style with the proper attributes.

In the rough sample below I'll try to point out style changes by writing pseudo-tags in square brackets (angle brackets are a hassle in Github). 'p:' represents a para style, 'c:' represents a char style, 'i' represents some manual italics, 'a:' represents some manual alignment change. 

```
[p:body]bla di bla [c:emphasis]blabla[/c:emphasis] bla di bla[/p:body]
[p:body][a:right]bla di bla [c:emphasis]blabla[/c:emphasis] bla di bla[/a:right][/p:body]
[p:body]bla di bla [i]blabla[/i] bla di bla[/p:body]
```

(Much detail is being skimped over, on purpose)

When the script runs, it would notice the alignment change on the second paragraph. It would try to find a para style 'based on' style 'body' but with right alignment. If none exists, it would create a brand new style (e.g. something like 'body_right'). 

The script would notice the manual italics, and also find that there is an existing character style which matches exactly with this manual styling. So, in this case it would change the manual italics to a character style. This behavior of finding and using an existing style could be made configurable: it might not always desirable to do a blanket replacement of a manual override with an existing style. In that case the script would create a new style even if a pre-existing user-created style exists.

After the script has run, the result would look like:
```
[p:body]bla di bla [c:emphasis]blabla[/c:emphasis] bla di bla[/p:body]
[p:body_right]bla di bla [c:emphasis]blabla[/c:emphasis] bla di bla[/p:body_right]
[p:body]bla di bla [c:emphasis]blabla[/c:emphasis] bla di bla[/p:body]
```

Ideas:
-  the script could also add some visual marker to any location where a change has happened (so you can search for the marker and inspect each change individually). 
- the script could also spit out some kind of human-readable text file with all the changes marked up so you can open this file in a text editor, and quickly read the content and judge whether the changes all make sense.

**Comment by zwettemaan** [comment]
Laura and Farrah: If this sounds reasonable, I could make a rough first version of said script so you can play with it and see whether it makes sense...

**Comment by LauraB7** [comment]
Sounds great, @zwettemaan. Do you imagine this will be an ID script or a post-export script. I worry a little about doing it in ID as I manage to get overrride from even  my extremely cleanly formatted InDesign files.

**Comment by zwettemaan** [comment]
My thinking was that this would be an ID script. It's possible it ends up being a dual operation (both post and pre), but I think it's a good start to make sure there are no 'manual overrides' in the doc - all changes in appearance or flow-mechanics should be driven by a named style. ID can then still make a mess of things, but at least there would be some order to the mess, or so I'd hope.

**Comment by zwettemaan** [comment]
@flittle8 @LauraB7 @kpjorgen 

I've written a first version which needs to be tested. I've only done some very cursory testing on a small document I concocted myself. Please have a read about the script here:

https://github.com/BCLibCoop/nnels-a11y-publishing/wiki/StyleCleanup-Script-Documentation

and then try it out.

I am interested in a few things:
- Does this approach sound sensible? 
- Does the use of GitHub for keeping the release version and the documentation work for you?
- Can you attach some sample documents for me to play with? My preference is for documents for which my first attempt at the script does *NOT* work.

There is a bunch more documentation in the Wiki; have a look. If you see any issues in the Wiki that you can fix or improve them yourself, please do: the whole idea of a Wiki is that anyone can contribute. All those spelling mistakes, I deliberately added those to keep y'all on yer toes ;-^ and you need to fix them as an exercise.

**Comment by LauraB7** [comment]
Hi Kris. I ran this script on the attached file -- an unmitigated mess of a book with almost no styles to begin with. I will attached the pre-script file, too, so you can see it. 

Some notes:
[Archive.zip](https://github.com/BCLibCoop/nnels-a11y-publishing/files/3050856/Archive.zip)

1. The copyright page changed to small caps? 
2. There was no Markdown file generated?
3. There are pieces of the file that the cleanup script missed, like the glossary.
4. It created a heck of a lot of style sheets. Is it overkill?

**Comment by zwettemaan** [comment]
Hi Laura,

I'll have a look, thanks! The first three points look like shortcomings of the script that need to be fixed.

I noticed you entered a list of issues. I'll convert those first three issues you found into separate GitHub issues. 

I really want to avoid getting 'to-do' lists lumped into a single GitHub issue. Otherwise, things become very hard to track...

If you have not done so, please make sure to read

https://github.com/BCLibCoop/nnels-a11y-publishing/wiki/How-To-Communicate-About-This-Project-Efficiently

Question: what are your thoughts on 

https://github.com/BCLibCoop/nnels-a11y-publishing/wiki/StyleCleanup-Script-Documentation

It explains my reasoning - which might or might not make sense.

There are a few aspects to the script: I think it is not possible for the script to determine what manual style changes are important and which ones are not. 

So the script is only half of the picture; the other half is a human operator who then takes the result of the script run and decides what each style is: relevant? irrelevant? the same as some other style?

Also, the script does not really know when two style changes are 'the same' and when not. To allow flexibility in that, the script is configurable. It ignores a lot of InDesign style info (e.g. it ignores tracking when comparing two style runs etc...), but it cannot really 'know'. It will depend on the job at hand.

So, the way I envision it to be used:

- The script picks up _all_ manual style changes that are relevant
- It lumps any manual style changes that are 'similar' into a single new style

The lumping mechanism reduces the number of artificial styles being created. There will still be a lot of them, but much less than without 'lumping together'

- The EBOOK creator now looks at the artificial styles and makes a judgment call. Is the style relevant? If not -> delete it. If it is -> see if it could be 'joined' with another style.

So, after running the script it is unavoidable that you need to go through the artificial styles and manually delete or merge them, until the document is 'clean'. The script cannot know what the styles are or why they are there (do they have meaning, or are they the result of an inexperienced InDesign user?).

If there are too many styles created, then the script needs to be reconfigured to ignore more irrelevant style differences (e.g. it can be told to ignore 'verticalScale' or something like that).

**Comment by zwettemaan** [comment]
Hi @LauraB7, I've made two videos which show how I envision this tool to be used. Have a look and let me know what you think.

Note, there is a new version available from (right-click and save):

https://raw.githubusercontent.com/BCLibCoop/nnels-a11y-publishing/master/ReleaseVersions/StyleCleanup.jsx

**Comment by zwettemaan** [comment]
The videos are in my DropBox, so please let me know when you've watched them, so I can eliminate them and free up the space.

Links to videos:
https://www.dropbox.com/s/9ignjv3z1qpx1tv/AttributeSelection.mp4?dl=0
https://www.dropbox.com/s/gvlkx4q3tz1fy8a/StyleCleanup.mp4?dl=0

**Comment by LauraB7** [comment]
These videos are great -- very clear explanation of your thinking. I am pleased to see you were as frustrated with the setup and layout of that file as I was. I have watched them both.

**Comment by zwettemaan** [comment]
I am moving these videos for future reference to a box.com account I am not using, so I can take them out of my DropBox folder. Eventually they'll need to 'go' somewhere, but this'll do for now:

https://app.box.com/s/iocqxxbcdvrfdhmktw0spgjjiqkfproi
